#!/usr/bin/env python3
"""Compile the pinned TSV snapshot using our own chess core (no pip packages).

Run on a POSIX development host: python3 tools/build_openings.py
Normal builds use the checked-in output and need neither Python nor network.
"""
import csv
import ctypes as C
import json
from pathlib import Path
import os
import shlex
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]

class Pos(C.Structure):
    _fields_ = [("sq", C.c_int8 * 64), ("stm", C.c_int8),
                ("castle", C.c_uint8), ("ep", C.c_int8),
                ("halfmove", C.c_int16), ("fullmove", C.c_int16)]

class Move(C.Structure):
    _fields_ = [("from_", C.c_uint8), ("to", C.c_uint8), ("promo", C.c_int8)]

with tempfile.TemporaryDirectory() as tmp:
    lib = Path(tmp) / "chess.so"
    subprocess.run(shlex.split(os.environ.get("CC", "cc")) +
                   ["-shared", "-fPIC", "-O2", "-std=c11", str(ROOT / "src/chess.c"),
                    "-o", str(lib)], check=True)
    chess = C.CDLL(str(lib))
    chess.pos_start.argtypes = [C.POINTER(Pos)]
    chess.san_to_move.argtypes = [C.POINTER(Pos), C.c_char_p, C.POINTER(Move)]
    chess.san_to_move.restype = C.c_bool
    chess.make_move.argtypes = [C.POINTER(Pos), Move]
    chess.pos_key.argtypes = [C.POINTER(Pos), C.POINTER(C.c_uint8 * 34)]
    nodes = [dict(children={}, move=0, label=0)]
    names = [""]
    name_labels = {"": 0}
    positions = {}
    rows = 0
    for volume in "abcde":
        with (ROOT / f"data/openings/{volume}.tsv").open() as f:
            for row in csv.DictReader(f, delimiter="\t"):
                rows += 1
                name = row["eco"] + " · " + row["name"]
                if name not in name_labels:
                    name_labels[name] = len(names)
                    names.append(name)
                label = name_labels[name]
                pos, move = Pos(), Move()
                chess.pos_start(C.byref(pos))
                node = 0
                for san in row["pgn"].split():
                    if san.endswith("."):
                        continue
                    if not chess.san_to_move(C.byref(pos), san.encode(), C.byref(move)):
                        raise ValueError(f"Invalid SAN {san}: {row}")
                    packed = move.from_ | (move.to << 6) | (move.promo << 12)
                    if packed not in nodes[node]["children"]:
                        nodes[node]["children"][packed] = len(nodes)
                        nodes.append(dict(children={}, move=packed, label=0))
                    node = nodes[node]["children"][packed]
                    chess.make_move(C.byref(pos), move)
                nodes[node]["label"] = label
                key = (C.c_uint8 * 34)()
                chess.pos_key(C.byref(pos), C.byref(key))
                # Stable first entry wins when multiple names share a position.
                positions.setdefault(bytes(key), label)
    assert len(nodes) < 65536 and len(names) < 65536
    siblings = {}
    for node in nodes:
        children = list(node["children"].values())
        for a, b in zip(children, children[1:]):
            siblings[a] = b
    lines = ["/* Generated by tools/build_openings.py. Data: Lichess, CC0. */",
             "static const OpeningNode opening_nodes[] = {"]
    for i, node in enumerate(nodes):
        child = next(iter(node["children"].values()), 0)
        lines.append(f'{{{child},{siblings.get(i, 0)},{node["move"]},{node["label"]}}},')
    lines += ["};", "static const OpeningPosition opening_positions[] = {"]
    for key, label in sorted(positions.items()):
        lines.append("{{{" + ",".join(map(str, key)) + "}}," + str(label) + "},")
    lines += ["};", "static const char opening_strings[] ="]
    offsets, offset = [], 0
    for name in names:
        offsets.append(offset)
        offset += len(name.encode()) + 1
        lines.append(json.dumps(name, ensure_ascii=False)[:-1] + '\\0"')
    lines += [";", "static const uint32_t opening_offsets[] = {",
              ",".join(map(str, offsets)), "};", ""]
    (ROOT / "src/openings_data.inc").write_text("\n".join(lines))
    print(f"{rows} lines, {len(names)-1} labels, {len(nodes)} nodes, {len(positions)} positions")
